#!/usr/bin/env bash

usage() {
  echo "Usage:"
  echo "  ms [command]"
  echo ""
  echo "Commands:"
  echo "  i - Install."
  echo "  d - Delete."
  echo "  c - Copy config."
}

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
target_dir="$XDG_DATA_HOME/archon"

command="$1"

if [[ "$command" == "i" ]]; then
  curl -sSL https://raw.githubusercontent.com/mrzli/archon/master/install.sh | bash
elif [[ "$command" == "d" ]]; then
  rm -rf "$target_dir"
elif [[ "$command" == "c" ]]; then
  "$target_dir/scripts/shared/copy-config"
else
  usage
  exit 1
fi
